# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Case Wall API
host: localhost
basePath: "/api"
definitions:
  Action:
    type: string
  Pattern:
    type: object
    properties:
      pattern:
        type: string
    required:
      - pattern
  Rule:
    type: object
    properties:
      map:
        type: string
      action:
        type: string
      event:
        type: string
    required:
      - action
      - event
      - map
# Describe your paths here
paths:
  /register:
    post:
      description: |
        register an account
      parameters:
        - name: credentials
          in: body
          description: |
            login credentials
          required: true
          schema:
            title: Credential
            properties:
              givenName:
                type: string
              surname:
                type: string
              username:
                type: string
              email:
                type: string
              password:
                type: string
            required:
              - givenName
              - surname
              - username
              - email
              - password
      responses:
        201:
          description: successfully created

  /login:
    post:
      description: |
        Login
      parameters:
        -
          name: credentials
          in: body
          description: Login credentials
          required: true
          schema:
            title: Case
            properties:
              username:
                type: string
              password:
                type: string
            required:
              - username
              - password
      responses:
        200:
          description: Successful login
          schema:
            title: successful
            properties:
              token:
                type: string

  /case:
    # This is a HTTP operation
    post:
      # Describe this verb here. Note: you can use markdown
      description: |
        Create a Case
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: case
          in: body
          description: Case to be created
          required: true
          schema: 
            title: Case
            properties:
              owner:
                type: string
              name:
                type: string
              users:
                type: array
                items:
                  type: string
              services:
                type: array
                items:
                  type: string
                  enum:
                    - github
                    - gdrive
                    - twitch
              resources:
                type: array
                items:
                  type: string
              patterns:
                type: array
                items:
                  type: string
              actions:
                type: array
                items:
                  type: string
                  

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
  /case/{id}/action/{aid}:
    post:
      description: |
        invoke an Action in this Case
      parameters:
        -
          name: id
          in: path
          type: string
        -
          name: aid
          in: path
          type: string
        # Response code
      responses:
        200:
          description: Successful response
          schema:
            title: Response
            properties:
              message:
                type: string
              response:
                type: string
  /case/{id}/action:
    get:
      description: |
        list the actions for this case
      parameters:
        -
          name: id
          in: path
          type: string
      responses:
        200:
          description: list of actions
          schema:
            title: Actions
            type: array
            items:
              $ref: '#/definitions/Action'
  /case/{id}/rule:
    get:
      description: |
        list the rules for this case
      parameters:
        -
          name: id
          in: path
          type: string
      responses:
        200:
          description: list of rules
          schema:
            title: Rules
            type: array
            items:
              $ref: '#/definitions/Rule'
    post:
      description: |
        add rule
      parameters:
        -
          name: id
          in: path
          type: string
        -
          name: Rule
          in: body
          required: true
          description: rule to be added
          schema:
            $ref: '#/definitions/Rule'
      responses:
        200:
          description: message
  /case/{id}/pattern:
    get:
      description: |
        list the patterns for this case
      parameters:
        -
          name: id
          in: path
          type: string
      responses:
        200:
          description: list of patterns
          schema:
            title: Patterns
            type: array
            items:
              $ref: '#/definitions/Pattern'
    post:
      description: |
        add pattern
      parameters:
        -
          name: id
          in: path
          type: string
        -
          name: Pattern
          in: body
          required: true
          description: rule to be added
          schema:
            $ref: '#/definitions/Pattern'
      responses:
        200:
          description: message        
          
          
